
services:
  db:
    image: postgres:bullseye
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: ./
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='${ADMIN_USER}').exists() or User.objects.create_superuser('${ADMIN_USER}', '${ADMIN_EMAIL}', '${ADMIN_PASSWORD}')\" | python manage.py shell &&
             DJANGO_SETTINGS_MODULE=begholplay.settings daphne -b 0.0.0.0 -p 8000 begholplay.asgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    expose:
      - 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
