# Generated by Django 4.1 on 2024-08-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
