# Generated by Django 4.1 on 2024-08-15 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0004_alter_player_color_alter_player_profile_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="creation_date",
            new_name="start_date",
        ),
        migrations.RenameField(
            model_name="player",
            old_name="color",
            new_name="favorite_color",
        ),
        migrations.RemoveField(
            model_name="lobby",
            name="users",
        ),
        migrations.RemoveField(
            model_name="match",
            name="players",
        ),
        migrations.AddField(
            model_name="lobby",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lobby",
            name="players",
            field=models.ManyToManyField(related_name="game_players", to="base.player"),
        ),
        migrations.AddField(
            model_name="match",
            name="board",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="match",
            name="current_turn",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="match",
            name="last_active_player",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lobby",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="lobby",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.lobby"
            ),
        ),
        migrations.CreateModel(
            name="Player_ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                ("score", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="base.lobby",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
