# Generated by Django 4.1 on 2024-08-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_rename_creation_date_match_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lobby",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lobby",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="favorite_color",
            field=models.CharField(
                choices=[
                    ("#DC143C", "RED"),
                    ("#Ffa500", "ORANGE"),
                    ("#4169E1", "BLUE"),
                    ("#228B22", "GREEN"),
                    ("#DAA520", "GOLDEN-ROD"),
                    ("#708090", "GRAY"),
                    ("#EE82EE", "VIOLET"),
                    ("#F4A460", "BROWN"),
                    ("#00FFFF", "CYAN"),
                ],
                default="#4169E1",
                max_length=20,
            ),
        ),
    ]
