# Generated by Django 4.1 on 2024-08-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_lobby_password_alter_lobby_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="in_lobby",
            field=models.BooleanField(default=False),
        ),
    ]
