# Generated by Django 4.1 on 2024-08-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_player_in_lobby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="default.jpg",
                null=True,
                upload_to="profile_photos/",
            ),
        ),
    ]
