# Generated by Django 4.1 on 2024-08-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_player_match_color_alter_player_favorite_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="favorite_color",
            field=models.CharField(
                choices=[
                    ("#DC143C", "RED"),
                    ("#FF6347", "TOMATO"),
                    ("#FF4500", "ORANGE RED"),
                    ("#Ffa500", "ORANGE"),
                    ("#DAA520", "GOLDEN-ROD"),
                    ("#FFD700", "GOLD"),
                    ("#FFFF00", "YELLOW"),
                    ("#ADFF2F", "GREEN YELLOW"),
                    ("#228B22", "GREEN"),
                    ("#32CD32", "LIME GREEN"),
                    ("#2E8B57", "SEA GREEN"),
                    ("#00FA9A", "MEDIUM SPRING GREEN"),
                    ("#20B2AA", "LIGHT SEA GREEN"),
                    ("#48D1CC", "MEDIUM TURQUOISE"),
                    ("#00FFFF", "CYAN"),
                    ("#00CED1", "DARK TURQUOISE"),
                    ("#5F9EA0", "CADET BLUE"),
                    ("#87CEFA", "LIGHT SKY BLUE"),
                    ("#6495ED", "CORNFLOWER BLUE"),
                    ("#4169E1", "BLUE"),
                    ("#6A5ACD", "SLATE BLUE"),
                    ("#8A2BE2", "BLUE VIOLET"),
                    ("#4B0082", "INDIGO"),
                    ("#9400D3", "DARK VIOLET"),
                    ("#9932CC", "DARK ORCHID"),
                    ("#EE82EE", "VIOLET"),
                    ("#DDA0DD", "PLUM"),
                    ("#C71585", "MEDIUM VIOLET RED"),
                    ("#FF69B4", "HOT PINK"),
                    ("#FF1493", "DEEP PINK"),
                    ("#FFB6C1", "LIGHT PINK"),
                    ("#F4A460", "BROWN"),
                    ("#D2691E", "CHOCOLATE"),
                    ("#8B4513", "SADDLE BROWN"),
                    ("#2F4F4F", "DARK SLATE GRAY"),
                    ("#708090", "GRAY"),
                    ("#008080", "TEAL"),
                    ("#191970", "MIDNIGHT BLUE"),
                    ("#B22222", "FIREBRICK"),
                ],
                default="#4169E1",
                max_length=20,
            ),
        ),
    ]
