# Generated by Django 5.1 on 2024-08-17 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_player_favorite_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player_ranking",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rankings",
                to="base.match",
            ),
        ),
    ]
